name: reconstruction-3v-${basename:${dataset.root_dir}}
tag: ""
seed: 42

dataset:
  name: dtu
  root_dir: ./sparsecraft_data/reconstruction/mvs_data/set0/scan55
  cameras_file: cameras.npz
  img_downscale: 1 # specify training image size by either img_wh or img_downscale
  apply_mask: false
  task: surface_reconstruction
  views_n: 3
  pcl_file: dense_3v/fused_3v.ply
  radius: ${model.radius}

model:
  name: sparsecraft
  radius: 1.0
  near_plane_bg: 0.1
  far_plane_bg: 10
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 1024
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 2048
  cos_anneal_end: ${trainer.max_steps}
  learned_background: true
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    grad_type: finite_difference
    finite_difference_eps: progressive
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 32
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 4
      finest_resolution: 2048
      include_xyz: true
      start_level: 1
      start_step: 0
      update_steps: 100
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  texture:
    name: disentangled-volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},6} # surface normals, input position and viewing direction as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 3
    color_activation: sigmoid
  # background model configurations
  num_samples_per_ray_bg: 64
  geometry_bg:
    name: volume-density
    radius: ${model.radius}
    feature_dim: 8
    density_activation: trunc_exp
    density_bias: -1
    isosurface: null
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16 # or 8
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 4 # or 8
      finest_resolution: 64
      include_xyz: true
      start_level: 1
      start_step: 0
      update_steps: 200
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
  texture_bg:
    name: volume-radiance
    input_feature_dim: ${model.geometry_bg.feature_dim}
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 3
    color_activation: sigmoid

system:
  name: sparsecraft-system
  loss:
    lambda_rgb_l1: 1.
    lambda_eikonal: 0.1
    lambda_mvs_color: [0, 0.001, 0.5, 4000]
    lambda_specular_color: [1500, 0.01, 0., 4000]
    lambda_input_taylor: [0, 0.001, 1., 4000]
    lambda_query_taylor: [0, 0.001, 1., 4000]
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      geometry_bg:
        lr: 0.01
      texture_bg:
        lr: 0.01
      variance:
        lr: 0.001
  constant_steps: 2000
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.constant_steps}
    schedulers:
      - name: ConstantLR
        args:
          factor: 1.0
          total_iters: ${system.constant_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.constant_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  export_mesh: True
  chunk_size: 2097152
  export_vertex_color: False

trainer:
  max_steps: 4000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  # val_check_interval: 1000
  limit_train_batches: 1.0
  limit_val_batches: 1
  # limit_test_batches: 1
  enable_progress_bar: true
  precision: 16
  deterministic: True
